// <auto-generated />
using System;
using FluentConfiguration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FluentConfiguration.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FluentConfiguration.Model.Units", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Units", (string)null);

                    b.HasDiscriminator<string>("UnitType").HasValue("Units");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FluentConfiguration.Model.Apartment", b =>
                {
                    b.HasBaseType("FluentConfiguration.Model.Units");

                    b.HasDiscriminator().HasValue("Apartment");
                });

            modelBuilder.Entity("FluentConfiguration.Model.House", b =>
                {
                    b.HasBaseType("FluentConfiguration.Model.Units");

                    b.HasDiscriminator().HasValue("House");
                });

            modelBuilder.Entity("FluentConfiguration.Model.Office", b =>
                {
                    b.HasBaseType("FluentConfiguration.Model.Units");

                    b.HasDiscriminator().HasValue("Office");
                });

            modelBuilder.Entity("FluentConfiguration.Model.Apartment", b =>
                {
                    b.OwnsOne("FluentConfiguration.Model.ApartmentAmenities", "ApartmentAmenities", b1 =>
                        {
                            b1.Property<Guid>("ApartmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("FloorNumber")
                                .IsRequired()
                                .HasColumnType("int");

                            b1.Property<bool?>("HasBalcony")
                                .IsRequired()
                                .HasColumnType("bit");

                            b1.HasKey("ApartmentId");

                            b1.ToTable("Units");

                            b1.WithOwner()
                                .HasForeignKey("ApartmentId");
                        });

                    b.Navigation("ApartmentAmenities")
                        .IsRequired();
                });

            modelBuilder.Entity("FluentConfiguration.Model.House", b =>
                {
                    b.OwnsOne("FluentConfiguration.Model.HouseAmenities", "HouseAmenities", b1 =>
                        {
                            b1.Property<Guid>("HouseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("HasGarge")
                                .IsRequired()
                                .HasColumnType("int");

                            b1.Property<int?>("NumberOfBedrooms")
                                .IsRequired()
                                .HasColumnType("int");

                            b1.HasKey("HouseId");

                            b1.ToTable("Units");

                            b1.WithOwner()
                                .HasForeignKey("HouseId");
                        });

                    b.Navigation("HouseAmenities")
                        .IsRequired();
                });

            modelBuilder.Entity("FluentConfiguration.Model.Office", b =>
                {
                    b.OwnsOne("FluentConfiguration.Model.OfficeAmenities", "OfficeAmenities", b1 =>
                        {
                            b1.Property<Guid>("OfficeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool?>("HasConferenceRoom")
                                .IsRequired()
                                .HasColumnType("bit");

                            b1.Property<int?>("NumberOfWorkspaces")
                                .IsRequired()
                                .HasColumnType("int");

                            b1.HasKey("OfficeId");

                            b1.ToTable("Units");

                            b1.WithOwner()
                                .HasForeignKey("OfficeId");
                        });

                    b.Navigation("OfficeAmenities")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
